// List of all shadcn components with their import paths
export const shadcnComponents = [
  { name: "Accordion", path: "@/components/ui/accordion" },
  { name: "Alert", path: "@/components/ui/alert" },
  { name: "AlertDialog", path: "@/components/ui/alert-dialog" },
  { name: "AspectRatio", path: "@/components/ui/aspect-ratio" },
  { name: "Avatar", path: "@/components/ui/avatar" },
  { name: "Badge", path: "@/components/ui/badge" },
  { name: "Breadcrumb", path: "@/components/ui/breadcrumb" },
  { name: "Button", path: "@/components/ui/button" },
  { name: "Calendar", path: "@/components/ui/calendar" },
  { name: "Card", path: "@/components/ui/card" },
  { name: "Carousel", path: "@/components/ui/carousel" },
  { name: "Chart", path: "@/components/ui/chart" },
  { name: "Checkbox", path: "@/components/ui/checkbox" },
  { name: "Collapsible", path: "@/components/ui/collapsible" },
  { name: "Combobox", path: "@/components/ui/combobox" },
  { name: "Command", path: "@/components/ui/command" },
  { name: "ContextMenu", path: "@/components/ui/context-menu" },
  { name: "DataTable", path: "@/components/ui/data-table" },
  { name: "DatePicker", path: "@/components/ui/date-picker" },
  { name: "Dialog", path: "@/components/ui/dialog" },
  { name: "Drawer", path: "@/components/ui/drawer" },
  { name: "DropdownMenu", path: "@/components/ui/dropdown-menu" },
  { name: "Form", path: "@/components/ui/form" },
  { name: "HoverCard", path: "@/components/ui/hover-card" },
  { name: "Input", path: "@/components/ui/input" },
  { name: "InputOTP", path: "@/components/ui/input-otp" },
  { name: "Label", path: "@/components/ui/label" },
  { name: "Menubar", path: "@/components/ui/menubar" },
  { name: "NavigationMenu", path: "@/components/ui/navigation-menu" },
  { name: "Pagination", path: "@/components/ui/pagination" },
  { name: "Popover", path: "@/components/ui/popover" },
  { name: "Progress", path: "@/components/ui/progress" },
  { name: "RadioGroup", path: "@/components/ui/radio-group" },
  { name: "Resizable", path: "@/components/ui/resizable" },
  { name: "ScrollArea", path: "@/components/ui/scroll-area" },
  { name: "Select", path: "@/components/ui/select" },
  { name: "Separator", path: "@/components/ui/separator" },
  { name: "Sheet", path: "@/components/ui/sheet" },
  { name: "Sidebar", path: "@/components/ui/sidebar" },
  { name: "Skeleton", path: "@/components/ui/skeleton" },
  { name: "Slider", path: "@/components/ui/slider" },
  { name: "Sonner", path: "@/components/ui/sonner" },
  { name: "Switch", path: "@/components/ui/switch" },
  { name: "Table", path: "@/components/ui/table" },
  { name: "Tabs", path: "@/components/ui/tabs" },
  { name: "Textarea", path: "@/components/ui/textarea" },
  { name: "Toast", path: "@/components/ui/toast" },
  { name: "Toggle", path: "@/components/ui/toggle" },
  { name: "ToggleGroup", path: "@/components/ui/toggle-group" },
  { name: "Tooltip", path: "@/components/ui/tooltip" },
]

// Helper function to check if a path is a shadcn component path
export function isShadcnComponentPath(path: string): boolean {
  return shadcnComponents.some((comp) =>
    path.includes(comp.path.replace("@/", "")),
  )
}
